void
func() {
  try {
  } catch (int errno) {
  }
  try {
  } catch (...) {
  }
}
